const {createRequire}=require('node:module');
const load=createRequire(process.argv[2]+'/package.json');
const {chromium}=load('playwright');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1600,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:7860',{waitUntil:'networkidle'});
 await page.locator('#emptyStage').waitFor({state:'visible'});
 await page.locator('#file').setInputFiles('runtime/upload_test_mirrored.mp4');
 await page.waitForFunction(()=>document.querySelector('#mediaTitle').textContent==='upload_test_mirrored.mp4',{timeout:180000});
 await page.locator('#start').fill('1');
 await page.locator('#start').dispatchEvent('change');
 await page.locator('#end').fill('3.5');
 await page.locator('#end').dispatchEvent('change');
 await page.evaluate(()=>{document.querySelector('#video').currentTime=2.25;});
 await page.waitForTimeout(800);
 const box=await page.locator('#picture').boundingBox();
 const response=page.waitForResponse(r=>r.url().endsWith('/api/editor/run')&&r.request().method()==='POST');
 await page.locator('#picture').click({position:{x:box.width*.5,y:box.height*.48}});
 const r=await response;const job=await r.json();if(r.status()!==202)throw Error(JSON.stringify(job));
 fs.writeFileSync('runtime/editor_test_job.json',JSON.stringify(job));
 console.log('SAM2 job '+job.id);
 await page.waitForFunction(()=>!document.querySelector('#generate').disabled,null,{timeout:240000});
 const details=await page.request.get('http://127.0.0.1:7860/api/job/'+job.id).then(r=>r.json());
 if(details.selection.frame_count!==41||details.selection.prompt_frame===0)throw Error('Dynamic duration or prompt frame failed');
 if(details.selection.media_id==='sample')throw Error('Uploaded source was not used');
 await page.screenshot({path:'runtime/EDITOR_PREVIEW.png',fullPage:true});
 await page.locator('#end').fill('3.25');await page.locator('#end').dispatchEvent('change');
 if(!await page.locator('#generate').isDisabled())throw Error('Stale mask was not invalidated');
 const bad=await page.request.post('http://127.0.0.1:7860/api/editor/run',{data:{...details.request,end:3.25,mode:'generate',selection_id:job.id,motion:'wave'}});
 if(bad.status()!==400)throw Error('Backend accepted stale selection');
 const range=await page.request.get('http://127.0.0.1:7860/assets/V58_Balanced.mp4',{headers:{Range:'bytes=0-99'}});
 if(range.status()!==206||(await range.body()).length!==100)throw Error('Byte ranges failed');
 if(errors.length)throw Error(errors.join('\n'));
 const report={ui:'pass',upload:'different mirrored test input, not independent quality dataset',selection_job:job.id,selection:details.selection,stale_selection_rejected:true,video_range:true,jsErrors:errors};
 fs.writeFileSync('runtime/EDITOR_TEST_REPORT.json',JSON.stringify(report,null,2));
 console.log(JSON.stringify({ui:'pass',selection_job:job.id,frame_count:41,prompt_frame:details.selection.prompt_frame,stale_selection_rejected:true,jsErrors:errors}));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
